# Generated by Django 3.2.5 on 2021-08-01 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('isDeleted', models.BooleanField()),
                ('profilePicUrl', models.CharField(max_length=250)),
                ('backgroundImageUrl', models.CharField(max_length=550)),
                ('isAccountNonExpired', models.BooleanField(default=False)),
                ('isEnabled', models.BooleanField(default=False)),
                ('isPro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='main.usuario')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='main.usuario')),
            ],
        ),
    ]
