# Generated by Django 3.2.5 on 2021-08-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='backgroundImageUrl',
            new_name='photo',
        ),
    ]
