# Generated by Django 3.2.5 on 2021-08-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_backgroundimageurl_usuario_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=550)),
                ('name', models.CharField(max_length=30)),
                ('IsInSolarSystem', models.BooleanField(default=True)),
                ('masa', models.IntegerField()),
                ('distancia', models.IntegerField()),
                ('radio', models.IntegerField()),
                ('description', models.CharField(max_length=550)),
                ('composicion', models.CharField(max_length=550)),
                ('astroTypes', models.TextField(blank=True, choices=[('Str', 'Estrella'), ('Plt', 'Planeta'), ('Sat', 'Satelite'), ('Com', 'cometa'), ('Ast', 'Asteroide'), ('Exo', 'Exoplaneta'), ('Glx', 'Galaxia'), ('Cum', 'Cumulo'), ('Scu', 'SuperCumulo')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitable', models.BooleanField(default=False)),
                ('astro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.astro')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=550)),
                ('like', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitable', models.BooleanField(default=False)),
                ('numSatelites', models.IntegerField()),
                ('planetType', models.TextField(blank=True, choices=[('Roc', 'Rocoso'), ('Gas', 'Gaseoso'), ('Nep', 'Neptuniano'), ('Pel', 'Planeta enano')], max_length=3, null=True)),
                ('astro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.astro')),
            ],
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starType', models.TextField(blank=True, choices=[('Hip', 'Hipergigante'), ('Spl', 'Supergigante luminosa'), ('Spg', 'Supergigante'), ('Gig', 'Gigante'), ('Sug', 'Sub-gigantes'), ('Enn', 'Enanas'), ('Sue', 'Sub-enanas'), ('Enb', 'Enanas blancas')], max_length=3, null=True)),
                ('astro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astro', to='main.astro')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=550)),
                ('time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
