# Generated by Django 3.2.5 on 2021-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usuario_profilepicurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='static/post/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profilePicUrl',
            field=models.ImageField(blank=True, upload_to='static/fotos_perfil/'),
        ),
    ]
