# Generated by Django 2.2.24 on 2021-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210812_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/eventos/'),
        ),
    ]
