# Generated by Django 2.2.24 on 2021-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210812_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='apuntados',
            field=models.ManyToManyField(to='main.Usuario'),
        ),
    ]
