# Generated by Django 2.2.24 on 2021-08-12 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210812_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='apuntados',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
